### ISSUE TITLE
which repo to use as master?

### ISSUE THREAD

**Issue by frisi** [tbenita/collective.zopeedit#1]
hi Thierry 

is https://github.com/collective/collective.zopeedit the master or yours?
asking since collective/collective.zopedit  is forked from your repos and yours has an issue tracker and the collective not.

shouldn't we enable the tracker on the collective one and close it here?

**Comment by frisi** [comment]
as you did the last commits on collevtive i'm asking you @mattss 
did you use this for ploneintranet? are there any newer binaries for osx and windows as

https://plone.org/products/zope-externaleditor-client/releases  (win)
and
http://www.atreal.net/solutions/atrealxnet/zopeedit.app-0.11.0.zip/view (macos - not compatible to plone4.3.7 version of externaleditor)

**Comment by mattss** [comment]
@frisi The collective fork of this is the most up to date one, as far as I'm aware. I did some work to support dexterity for ploneintranet there, which is in master.

Also did some packaging work to allow the windows client to be built using more up to date tools - see this branch which is not yet merged: https://github.com/collective/collective.zopeedit/tree/packaging-updates

**Comment by tbenita** [comment]
Hi all, this repo will be closed in order to leave collective as new root of the project on github.
Cheers
